### ISSUE TITLE
Directory structure not compatible with composer

### ISSUE THREAD

**Issue by valthebald** [drupal-cod/cod_kickstart#1]
Having full site structure (including tools like BLT) in repository root makes it harder to include distribution as a whole to another project.

Suggestion: follow the structure of social distribution http://cgit.drupalcode.org/social/tree/

**Comment by valthebald** [comment]
Here's the PR https://github.com/drupal-cod/cod/pull/2

**Comment by mikemadison13** [comment]
@valthebald we are planning on this part of the project being, itself, a complete distribution that you can pull down to work on on COD, not necessarily a component that you would include in another project/distro. That would be the https://github.com/drupal-cod/cod repo that will be the one that you can pull down and include in another project (although, admittedly, there isn't much there yet).
